default: &default
  adapter: postgresql
  pool: 5
  user: "postgres"
  password: "postgres"
  host: db

development:
  <<: *default
  database: onebitfood-api_development

test:
  <<: *default
  database: onebitfood-api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>